---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  #namespace: sprint
  labels:
   app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql
...
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
    # terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: rajmandale/bookmyslot:mysql
        
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: 'Password'
          - name: MYSQL_DATABASE
            value: 'userdb'
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: 'true'
          - name: MYSQL_PASSWORD
            value: 'root'
...
